<?php 
if(isset($_REQUEST['CId'])&&isset($_REQUEST['tId']))
{
	header("location:https://github.com/Soniyathomas/web_shirtgen/");
}
else
{
	header("location:https://github.com/wordpressmonk/web_retargetbomb/");
}
?>
